services:
  php-74-cli:
    build:
      context: docker/php/74-cli
      dockerfile: Dockerfile
    volumes:
      - .:/opt/project
  php-74-fpm:
    build:
      context: docker/php/74-fpm
      dockerfile: Dockerfile
    volumes:
      - .:/opt/project
  nginx-php-74:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/opt/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-74-fpm
  postgres:
    image: postgres:15
    container_name: psql
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
volumes:
  postgres_data:

#  db:
#    image: mariadb:latest
#    container_name: db
#    restart: always
#    environment:
#      MARIADB_DATABASE: meubanco
#      MARIADB_USER: meuusuario
#      MARIADB_PASSWORD: senha123
#    ports:
#      - "3306:3306"
#    volumes:
#      - mariadb_data:/var/lib/mysql
#
#volumes:
#  mariadb_data: